version: '3'

services:
  db:
    container_name: finwise_database
    image: postgres
    environment: 
      - POSTGRES_DB=finwiseDB
      - POSTGRES_USER=finwise
      - POSTGRES_PASSWORD=5f1_glMF_b%sX!z%o-Y0FbTMI828q2KM
    networks: 
      - main
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  backend: &backend
    container_name: backendServer
    build:
      context: ./backend
      #dockerfile: scripts/prod/Dockerfile

    command: /start_prod.sh
    volumes:
      - ./backend:/backend
      - django-static:/backend/static
    networks:
      - main
    depends_on:
      - db
  asgiserver:
    <<: *backend
    container_name: asgiServer
    entrypoint: /start_asgi.sh
    volumes: 
      - ./backend:/backend

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/prod/Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - main
    volumes:
      - django-static:/usr/src/app/static
      - nginxConf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - main
    
volumes:
  django-static:
  portainer-data:
  pg-data:
  redis-data:
  nginxConf:

networks:
  main:
    driver: bridge
    